# DB_PASSWORD=foobar docker compose up -d --build --force-recreate

services:
  crypto-db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  crypto-app:
    build: { context: . }
    ports: ["${PORT}:80"]
    depends_on:
      crypto-db: { condition: service_healthy }
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: crypto-db
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: 80

volumes:
  db_data:
